name: dartXMLParse
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
dependencies: 
  archive: ^3.1.2
  http: ^0.13.0
  unicode: ^0.3.0
  xml: ^5.0.2
